### ISSUE TITLE
need to give feedback when loading page

### ISSUE THREAD

**Issue by blairmacintyre** [argonjs/argon-app#34]
Right now, if I go to a page (like our samples page) and click on one of the links, I get no feedback until the page loads.

I've received feedback from a few folks that with no "active" progress feedback, it feels like it has crashed or hung

Possible kinds of feedback:
- something to indicate the click was received to go to the new page.  Changing the URL in the url bar immediately helps (we do that), but something else.  A spinner or other loading indication?  What can we find out from the wkwebview while it's loading?  Can we do a load meter somewhere?
- could we clear the content?

**Comment by kimberlysiva** [comment]
Complete
