### ISSUE TITLE
ability to hide UI, in landscape mode or otherwise

### ISSUE THREAD

**Issue by blairmacintyre** [argonjs/argon-app#39]
Playing with the AFrame demos (aframe.io) in mobile Safari, I really like how they switch to full-screen mode when you rotate the phone.  There are menus, decoration, etc., in portrait, but nothing in landscape.

At least in Mobile safari.   In argon, the URL bar is still there.

We should support this properly.  Can someone look into how this works on mobile safari?  It would be nice if we could support this, and enable apps to behave like this.  This also means we could support typical "cardboard" web apps more cleanly (allowing people to create website that support AR and VR).

**Comment by kimberlysiva** [comment]
Complete
