### ISSUE TITLE
vuforia target tracking not tightly aligned on Samsung S6 

### ISSUE THREAD

**Issue by blairmacintyre** [argonjs/argon-app#72]
Not sure if this is true for all android phones, or just some, but the alignment between the content and the target is not as tight on the S6 as on iOS devices.

**Comment by kimberlysiva** [comment]
Created a glitch to test alignment: http://testalign-aframe-vuforia.glitch.me/

Tested on Pixel, Galaxy 7, and iPhone 6 with reasonable results.
