### ISSUE TITLE
More visual feedback during loading pages

### ISSUE THREAD

**Issue by blairmacintyre** [argonjs/argon-app#77]
Right now there is no feedback or progress during loading or refresh.  It would be very helpful to have immediate (and ongoing) indication that something is happening

**Comment by speigg** [comment]
Our ArgonWebView plugin is already exposing progress, is this should be pretty simple to add (if anyone wants to give it a go)

**Comment by blairmacintyre** [comment]
Detailed progress would be great;  but, even having feedback that something is happening.  For example:
- I hit refresh: there is no indication Argon4 has started doing that.  We should consider things like a spinner, etc. ... something that appears immediately just to indicate "Hey, I registered the action, I'm working on it"
- I type a URL and hit return.  Same deal.  I have no idea if anything is happening, typically for a second or two ... longer if i mistyped and it's hung waiting for a timeout!

**Comment by kimberlysiva** [comment]
Complete
