### ISSUE TITLE
vuforia tracking data and multiple channels

### ISSUE THREAD

**Issue by blairmacintyre** [argonjs/argon-app#80]
If I run multiple pages that use Vuforia, there are problems:
- switching between the pages does not seem to switch which dataset is being tracked (the front one should be used).  The last one used seems to continue being used, and the data continuing to be sent to that page
- if there are multiple pages that use the same target set, all pages get the data.  I guess that is fine?  I assume the determination is made based on the URL of the dataset?
- deleting a page using vuforia and going back to a page that was using a different dataset crashes the app.

I understand that there are issues with shutting down and reinitializing vuforia frequently when apps switch around.  We may need to consider how to deal with this more creatively (e.g., perhaps we switch to new vuforia contexts when loading new pages, but require the user to switch which page is tracking, perhaps by adding a menu item to a page with Vuforia tracking that says "re-start vuforia" or something).  "Robust" is better than "elegant"

**Comment by speigg** [comment]
Now fixed. Switching between licenses stalls the app by about 0.5 seconds. Might be able to move some of the work to another thread in the future to minimize the impact on the UI.

**Comment by speigg** [comment]
> if there are multiple pages that use the same target set, all pages get the data. I guess that is fine? I assume the determination is made based on the URL of the dataset?

Yes, it's based on the url of the dataset
